# Generated by Django 5.2.13 on 2026-04-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='session_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
