# Generated by Django 5.2.13 on 2026-04-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_file_name_document_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
