# Generated by Django 5.2.13 on 2026-04-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='page_number',
            field=models.IntegerField(),
        ),
    ]
