sonar.projectKey=Vamshee2703_pdfchatbot
sonar.organization=vamshee2703

sonar.sources=backend,frontend
sonar.tests=backend/api
sonar.test.inclusions=backend/**/tests.py,backend/**/*test*.py
sonar.exclusions=**/node_modules/**,**/.next/**,backend/venv/**,**/migrations/**,**/__pycache__/**,backend/bandit-report.json

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.sourceEncoding=UTF-8
